source 'https://rubygems.org'


gem 'mysql2'
gem 'rails', '4.1.14.2'

group :development do
  gem 'spring'
end

group :test do
  gem "rspec-rails", "~> 3.4.2"
  gem 'factory_girl_rails'
  gem 'pry-rails'
end
